# Generated by Django 3.2.4 on 2021-06-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(blank=True, max_length=225, null=True)),
                ('dob', models.CharField(blank=True, max_length=225, null=True)),
                ('sex', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=225, null=True)),
                ('level', models.CharField(blank=True, choices=[('JSS1', 'JSS1'), ('JSS2', 'JSS2'), ('JSS3', 'JSS3'), ('SS1', 'SS1'), ('SS2', 'SS2'), ('SS3', 'SS3')], max_length=225, null=True)),
                ('addmin_no', models.CharField(blank=True, max_length=225, null=True)),
                ('address', models.CharField(blank=True, max_length=555, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive')], max_length=555, null=True)),
                ('father_no', models.CharField(blank=True, max_length=225, null=True)),
                ('father_email', models.CharField(blank=True, max_length=225, null=True)),
                ('mother_no', models.CharField(blank=True, max_length=225, null=True)),
                ('mother_email', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
    ]
