# Generated by Django 3.2.4 on 2021-06-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsms', '0004_auto_20210626_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_reg',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
